In [1]:
# numpy are used to create multi dimensional arrays 
# array operationns are faster in eda
#saves memeory

import numpy as np

In [2]:
#np.array - creates the array
my_list = [1,2,3,4,5,6,7,8]
ny_array = np.array(my_list)

In [3]:
print(ny_array)

[1 2 3 4 5 6 7 8]


In [4]:
type(ny_array)

numpy.ndarray

In [5]:
ny_array.shape

(8,)

In [6]:
ny_array.reshape(2,4) # create into list into array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
ny_array1 = [1,3,4,5,6]
ny_array2 = [2,5,3,6,7]
ny_array3 = [3,6,7,8,9]

In [21]:
arr = np.array([ny_array1,ny_array2,ny_array3])  

In [30]:
arr[1:2,1:4] # accessing different elements in multidimensiaonal array

array([[5, 3, 6]])

In [27]:
arr[1:,1:3]

array([[5, 3],
       [6, 7]])

In [24]:
arr[1:,3:] ## accessing array values through indexing , arrays have two columns rows,column indexing

array([[6, 7],
       [8, 9]])

In [22]:
arr.shape

(3, 5)

In [12]:
arr.reshape(2,3) # one dimesnional arrya [],two dimensional array [[]], multi diemsional array [[[]]]

array([[1, 3, 2],
       [5, 3, 6]])

In [13]:
arr.shape

(3, 2)

In [17]:
#### indexing - accessing array elements 
arr_1 = np.array([1,2,3,4,5,6])
arr_1[5]

6

In [18]:
arr_1

array([1, 2, 3, 4, 5, 6])

In [33]:
# in bulit functions in numpy
np.arange  # arrabges tehe array in order
np.arange(0,10,step=3) # arages in order with step 3 of items

array([0, 3, 6, 9])

In [35]:
# broadcasting or copying 
arr_1

array([1, 2, 3, 4, 5, 6])

In [36]:
arr_1[4:]= 100 # assigning elemnts by replacing through indexing

In [37]:
arr_1

array([  1,   2,   3,   4, 100, 100])

In [42]:
# some conditions are usefull in EDA
val = 2
arr_1 <2
arr_1*2
arr_1[arr_1<50]

array([1, 2, 3, 4])

In [45]:
np.ones(5,dtype=int) # all the elemensts are replaced by ones

array([1, 1, 1, 1, 1])

In [47]:
np.ones((3,3),dtype=float) # float dtypes

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
# random distribution # creates the random samples with uniform distribution with shape
np.random.rand(3,3)

array([[0.61776313, 0.16223426, 0.98763002],
       [0.15337365, 0.75305516, 0.62463974],
       [0.35657152, 0.2376413 , 0.23839984]])

In [49]:
np.random.rand(4,5)

array([[0.75764101, 0.94507641, 0.70109216, 0.09161185, 0.37007594],
       [0.50478966, 0.08237975, 0.85099549, 0.92694934, 0.93057608],
       [0.72724609, 0.534693  , 0.90067375, 0.25533981, 0.12566161],
       [0.41267828, 0.90692261, 0.63147811, 0.21464587, 0.90467264]])

In [52]:
#randn - returns the sample output from standard normal distributio
arr_exp = np.random.randn(4,4)

In [53]:
arr_exp

array([[ 0.47655192, -0.63779567,  0.6150182 , -0.24620255],
       [ 1.44757824, -0.2317679 , -1.08761375,  0.17045587],
       [ 0.82119932,  0.27748638, -0.79995531,  0.72344197],
       [ 0.7586238 ,  0.21535553,  0.52228982,  0.6704709 ]])

In [54]:
#https://www.youtube.com/results?search_query=krish+naik+numpy